defaultCypressOrbConfig: &defaultCypressOrbConfig
  executor: 
    name: cypress/default
    node-version: '18.17.1'

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  # see https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@3.1.4
jobs:
  install-and-persist:
    <<: *defaultCypressOrbConfig
    steps:
      - cypress/install:
          install-command: yarn
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  run-tests:
    <<: *defaultCypressOrbConfig
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          start-command: npm run start
          cypress-command: NODE_ENV=test npm run cypress:run
      - run: npm run report:coverage:summary
      - run: npm run report:coverage:text
      # send code coverage to coveralls.io
      # https://coveralls.io/github/cypress-io/cypress-example-todomvc-redux
      # our coveralls account is currently not enabled 
      # - run: npm run coveralls

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - install-and-persist
      - run-tests:
          requires: 
            - install-and-persist
